name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: go build -v ./...

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Lint
      uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b # v3.7.1
      with:
        version: v1.55

  unit-test:
    name: Unit Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Test
      run: go test -v -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        verbose: true

  integration-test:
    name: Integration Test
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    services:
      backstage:
        image: roadiehq/community-backstage-image
        ports:
          - 7000
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Run entities example
      env:
        BACKSTAGE_BASE_URL: http://localhost:${{ job.services.backstage.ports[7000] }}/api
      run: |
        sleep 30
        go run ./examples/entities/main.go
    - name: Run locations example
      env:
        BACKSTAGE_BASE_URL: http://localhost:${{ job.services.backstage.ports[7000] }}/api
      run: |
        sleep 30
        go run ./examples/locations/main.go
